import { expect, test } from '@playwright/test'

test('entra a la demo y navega por las áreas principales', async ({ page }) => {
  await page.goto('/')
  const demoButton = page.getByRole('button', { name: /probar con datos de ejemplo/i })
  await expect(demoButton).toBeVisible()
  await demoButton.click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.getByRole('link', { name: 'Actividad' }).click()
  await expect(page).toHaveURL(/\/actividad$/)
  await expect(page.getByRole('heading', { name: 'Actividad' })).toBeVisible()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await expect(page).toHaveURL(/\/plan$/)
  await expect(page.getByRole('heading', { name: 'Tu plan' })).toBeVisible()
})

test('muestra el resumen rápido de metas, compras y cuentas en Inicio', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: 'Metas', exact: true })).toBeVisible()
  await expect(page.getByText('Un viaje especial')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Próximas compras', exact: true })).toBeVisible()
  await expect(page.getByText('Sin compras anotadas')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Cuentas', exact: true })).toBeVisible()
  await expect(page.getByText('Cuenta principal', { exact: true })).toBeVisible()
})

test('registra un plan opcional de deuda y configura los ingresos de referencia', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.goto('/cuentas')
  await page.getByRole('button', { name: 'Agregar' }).click()
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta' })
  await accountDialog.getByLabel('Nombre').fill('Libre inversión')
  await accountDialog.getByLabel('Naturaleza').selectOption('liability')
  await accountDialog.getByLabel('Tipo de deuda').selectOption('investment_loan')
  await accountDialog.getByLabel('Deuda inicial').fill('1.200.000')
  await accountDialog.getByLabel('Total de cuotas').fill('12')
  await accountDialog.getByLabel('Cuotas pagadas').fill('2')
  await accountDialog.getByLabel('Valor de cada cuota').fill('100.000')
  await accountDialog.getByLabel('Cada cuánto la pagas').selectOption('monthly')
  await accountDialog.getByRole('button', { name: 'Crear cuenta' }).click()
  await expect(page.getByRole('heading', { name: 'Libre inversión', exact: true })).toBeVisible()
  await expect(page.getByText(/2 de 12 cuotas · .* cada mes/)).toBeVisible()

  await page.goto('/ajustes')
  await page.getByLabel('Sueldo mensual equivalente').fill('3.200.000')
  await page.getByLabel('¿Cada cuánto recibes tu pago?').selectOption('monthly')
  await page.getByRole('button', { name: 'Guardar ingresos' }).click()
  await expect(page.getByText('Ingresos guardados')).toBeVisible()
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Mis ingresos', exact: true })).toBeVisible()
  await expect(page.locator('.income-summary').getByText(/3\.200\.000/)).toBeVisible()
})

test('no produce desplazamiento horizontal', async ({ page }) => {
  await page.goto('/')
  const demoButton = page.getByRole('button', { name: /probar con datos de ejemplo/i })
  await expect(demoButton).toBeVisible()
  await demoButton.click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('registra un gasto y lo conserva al recargar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.getByRole('textbox', { name: /Monto/i }).fill('10.000')
  await page.getByLabel(/Categoría/).selectOption({ label: 'Mascotas' })
  await page.getByRole('textbox', { name: /Comercio o nota/i }).fill('Compra de prueba')
  await page.getByRole('button', { name: 'Guardar movimiento' }).click()
  await page.getByRole('link', { name: 'Actividad' }).click()
  await expect(page.getByText('Compra de prueba')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Compra de prueba')).toBeVisible()
})

test('oculta montos y aplica las preferencias de tema y movimiento', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: /ajustes/i }).first().click()
  await page.getByRole('switch', { name: 'Ocultar montos' }).click()
  await page.getByRole('combobox').first().selectOption('dark')
  await page.getByRole('combobox').nth(1).selectOption('off')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'off')
  await page.getByRole('link', { name: 'Inicio' }).click()
  await expect(page.getByText('••••••').first()).toBeVisible()
})

test('abre notificaciones sin solicitar permiso automáticamente', async ({ page }) => {
  await page.addInitScript(() => {
    window.__permissionRequests = 0
    class TestNotification {}
    TestNotification.permission = 'default'
    TestNotification.requestPermission = async () => { window.__permissionRequests += 1; return 'default' }
    Object.defineProperty(window, 'Notification', { value: TestNotification, configurable: true })
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Probar con datos de ejemplo' }).click()
  await page.goto('/ajustes/notificaciones')
  await expect(page.getByRole('heading', { name: 'Avisos privados de PataWallet' })).toBeVisible()
  await expect(page.getByText('Solo para cuentas reales')).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.__permissionRequests)).toBe(0)
})

test('mantiene el foco dentro del movimiento y lo devuelve al cerrar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  const opener = page.getByRole('button', { name: 'Nuevo movimiento' })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Nuevo movimiento' })
  await expect(dialog).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar' }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.locator(':focus')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()
})

test('mantiene acciones accesibles en horizontal y con texto ampliado', async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.addStyleTag({ content: 'html { font-size: 200% !important; }' })
  const save = page.getByRole('button', { name: 'Guardar movimiento' })
  await save.scrollIntoViewIfNeeded()
  await expect(save).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('cierra y guarda las ventanas de metas', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: /nueva meta/i }).click()
  await expect(page.getByRole('dialog', { name: 'Nueva meta' })).toBeVisible()
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByRole('button', { name: 'Cerrar' }).click()
  await expect(page.getByRole('dialog', { name: 'Nueva meta' })).toBeHidden()
  await page.getByRole('button', { name: /nueva meta/i }).click()
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByLabel('Nombre').fill('Viaje familiar')
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByLabel('Monto objetivo').fill('500.000')
  await page.getByRole('button', { name: 'Crear meta' }).click()
  await expect(page.getByRole('heading', { name: 'Viaje familiar' })).toBeVisible()
})

test('crea categoría, hora y comprobante opcionales', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.getByRole('button', { name: 'Crear categoría' }).click()
  const categoryDialog = page.getByRole('dialog', { name: 'Nueva categoría' })
  await categoryDialog.getByLabel('Nombre').fill('Educación')
  await categoryDialog.getByRole('button', { name: 'Crear categoría' }).click()
  await expect(page.locator('.field').filter({ hasText: /^Categoría/ }).locator('select')).toHaveValue(/category/)
  await page.getByRole('textbox', { name: /Monto/i }).fill('25.000')
  await page.getByLabel('Hora').fill('18:45')
  await page.locator('input[type=file]').setInputFiles({ name: 'comprobante.png', mimeType: 'image/png', buffer: Buffer.from('89504e470d0a1a0a', 'hex') })
  await expect(page.getByAltText('Vista previa del comprobante')).toBeVisible()
  await page.getByRole('button', { name: 'Guardar movimiento' }).click()
  await expect(page.getByText('Movimiento guardado')).toBeVisible()
})

test('agrega y evalúa una próxima compra sin crear gasto', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Agregar' }).click()
  const dialog = page.getByRole('dialog', { name: 'Agregar próxima compra' })
  await dialog.getByLabel('Compra').fill('Audífonos')
  await dialog.getByLabel('Monto estimado').fill('120.000')
  await dialog.getByRole('button', { name: 'Guardar próxima compra' }).click()
  await expect(page.getByRole('heading', { name: 'Audífonos' })).toBeVisible()
  await expect(page.getByText(/presupuesto|fondos registrados/i).last()).toBeVisible()
})
