import { expect, test } from '@playwright/test'

test('entra a la demo y navega por las áreas principales', async ({ page }) => {
  await page.goto('/')
  const demoButton = page.getByRole('button', { name: /probar con datos de ejemplo/i })
  await expect(demoButton).toBeVisible()
  await demoButton.click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.getByRole('link', { name: 'Actividad' }).click()
  await expect(page).toHaveURL(/\/actividad$/)
  await expect(page.getByRole('heading', { name: 'Actividad' })).toBeVisible()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await expect(page).toHaveURL(/\/plan$/)
  await expect(page.getByRole('heading', { name: 'Metas y plan' })).toBeVisible()
})

test('abre el asistente desde la burbuja flotante', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('link', { name: 'Abrir asistente' })).toBeVisible()
  await page.getByRole('link', { name: 'Abrir asistente' }).click()
  await expect(page).toHaveURL(/\/asistente$/)
  await expect(page.getByRole('heading', { name: 'Asistente PataWallet' })).toBeVisible()
})

test('completa el punto de partida y calcula el dinero libre', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Configurar mi espacio' }).click()
  await expect(page.getByRole('heading', { name: 'Hagamos cuentas con calma.' })).toBeVisible()
  await page.getByRole('textbox', { name: /Salario mensual equivalente/i }).fill('3.200.000')
  await page.getByRole('combobox', { name: '¿Cada cuánto recibes tu pago?' }).selectOption('monthly')
  const salaryAccountInput = page.getByRole('textbox', { name: 'Nombre de la cuenta donde recibes el salario' })
  if (!(await salaryAccountInput.isVisible())) await page.getByRole('combobox', { name: 'Cuenta donde recibes el salario' }).selectOption('__new_account__')
  await salaryAccountInput.fill('Ahorros Bancolombia')
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Agregar deuda' }).click()
  await page.getByLabel('Nombre').fill('Tarjeta principal')
  await page.getByLabel('Total pendiente').fill('1.200.000')
  await page.getByLabel('Pago mensual').fill('100.000')
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByLabel('Nombre').fill('Arriendo')
  await page.getByLabel('Monto mensual').fill('900.000')
  await page.getByRole('button', { name: 'Agregar gasto fijo' }).click()
  await page.getByLabel('Nombre').nth(1).fill('Internet')
  await page.getByLabel('Monto mensual').nth(1).fill('100.000')
  await expect(page.getByText('Dinero libre mensual estimado')).toBeVisible()
  await expect(page.getByText('$ 2.100.000')).toBeVisible()
  await page.getByRole('button', { name: 'Ver mi dinero libre' }).click()
  await expect(page.getByRole('heading', { name: /Hola,/i })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Dinero libre este mes' })).toBeVisible()
  await page.goto('/cuentas')
  await expect(page.getByRole('heading', { name: 'Ahorros Bancolombia', exact: true })).toBeVisible()
})

test('muestra el resumen rápido de metas, compras y cuentas en Inicio', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: 'Metas', exact: true })).toBeVisible()
  await expect(page.getByText('Un viaje especial')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Próximas compras', exact: true })).toBeVisible()
  await expect(page.getByText('Sin compras anotadas')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Cuentas', exact: true })).toBeVisible()
  await expect(page.getByText('Cuenta principal', { exact: true })).toBeVisible()
})

test('cambia y recuerda las tres vistas de Inicio', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  const views = page.getByRole('group', { name: 'Vistas de Inicio' })
  await expect(views.getByRole('button', { name: 'Saldo claro' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('Dinero libre este mes').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)

  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  const fixedExpenses = page.locator('.fixed-expenses-section')
  await fixedExpenses.getByRole('button', { name: 'Gastos fijos', exact: true }).click()
  await fixedExpenses.getByLabel('Nombre').fill('Internet de prueba')
  await fixedExpenses.getByLabel('Monto mensual').fill('80.000')
  await fixedExpenses.getByRole('button', { name: 'Guardar gastos fijos' }).click()
  await expect(page.getByText('Gastos fijos guardados')).toBeVisible()
  await page.getByRole('link', { name: 'Inicio', exact: true }).click()

  await views.getByRole('button', { name: 'Quincena' }).click()
  await expect(page.getByRole('heading', { name: 'Tu fecha de pago' })).toBeVisible()
  await expect(views.getByRole('button', { name: 'Quincena' })).toHaveAttribute('aria-pressed', 'true')
  const payment = page.getByRole('checkbox', { name: /Marcar Internet de prueba del .* como pagado/ }).first()
  await expect(payment).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.reload()
  await expect(views.getByRole('button', { name: 'Quincena' })).toHaveAttribute('aria-pressed', 'true')
  const recurringPayment = page.getByRole('checkbox', { name: /Marcar Internet de prueba del .* como pagado/ }).first()
  await expect(recurringPayment).not.toBeChecked()
  await recurringPayment.click()
  await expect(recurringPayment).toBeChecked()

  await views.getByRole('button', { name: 'Actividad' }).click()
  await expect(page.getByRole('heading', { name: 'Gastos por categoría' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Actividad' })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('registra un plan opcional de deuda y configura los ingresos de referencia', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.goto('/cuentas')
  await page.getByRole('button', { name: 'Agregar deuda', exact: true }).click()
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta' })
  await expect(accountDialog.getByLabel('Naturaleza')).toHaveValue('liability')
  await accountDialog.getByLabel('Nombre').fill('Libre inversión')
  await accountDialog.getByLabel('Tipo de deuda').selectOption('investment_loan')
  await accountDialog.getByLabel('Deuda inicial').fill('1.200.000')
  await accountDialog.getByLabel('Total de cuotas').fill('12')
  await accountDialog.getByLabel('Cuotas pagadas').fill('2')
  await accountDialog.getByLabel('Valor de cada cuota').fill('100.000')
  await accountDialog.getByLabel('Cada cuánto la pagas').selectOption('monthly')
  await accountDialog.getByRole('button', { name: 'Crear cuenta' }).click()
  await expect(page.getByRole('heading', { name: 'Libre inversión', exact: true })).toBeVisible()
  await expect(page.getByText(/2 de 12 cuotas · .* cada mes/)).toBeVisible()

  const fixedExpenses = page.locator('.fixed-expenses-section')
  await expect(fixedExpenses.locator('form')).toHaveCount(0)
  await fixedExpenses.getByRole('button', { name: 'Gastos fijos', exact: true }).click()
  await fixedExpenses.getByLabel('Nombre').fill('Arriendo')
  await fixedExpenses.getByLabel('Monto mensual').fill('900.000')
  await fixedExpenses.getByRole('button', { name: 'Guardar gastos fijos' }).click()
  await expect(page.getByText('Gastos fijos guardados')).toBeVisible()
  await expect(fixedExpenses.getByRole('heading', { name: 'Checklist de pagos', exact: true })).toBeVisible()
  const paidExpense = fixedExpenses.getByRole('checkbox', { name: 'Marcar Arriendo como pagado' }).first()
  await expect(paidExpense).toBeVisible()
  await paidExpense.click()
  await expect(page.getByText('Arriendo marcado como pagado')).toBeVisible()
  await expect(paidExpense).toBeChecked()
  await fixedExpenses.getByRole('button', { name: 'Guardar gastos fijos' }).click()
  await expect(page.getByText('Gastos fijos guardados')).toBeVisible()
  await expect(fixedExpenses.getByRole('checkbox', { name: 'Marcar Arriendo como pagado' }).first()).toBeChecked()

  const incomeSection = page.locator('.income-section')
  await expect(incomeSection.locator('form')).toHaveCount(0)
  await incomeSection.getByRole('button', { name: 'Ingresos', exact: true }).click()
  await incomeSection.getByLabel('Nombre del ingreso').fill('Salario')
  await incomeSection.getByLabel('Cuenta donde recibes el ingreso').selectOption({ label: 'Cuenta principal' })
  await incomeSection.getByLabel('Sueldo mensual equivalente').fill('3.200.000')
  await incomeSection.getByLabel('¿Cada cuánto recibes tu pago?').selectOption('monthly')
  await incomeSection.getByRole('button', { name: 'Guardar ingresos' }).click()
  await expect(page.getByText('Ingresos guardados')).toBeVisible()

  await page.goto('/ajustes')
  await expect(page.getByRole('heading', { name: 'Ingresos', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Gastos fijos', exact: true })).toHaveCount(0)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Mis ingresos', exact: true })).toBeVisible()
  await expect(page.locator('.income-summary').getByText(/3\.200\.000/)).toBeVisible()
})

test('muestra el acceso al asistente y protege la demo', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.goto('/ajustes')
  await expect(page.getByRole('link', { name: /asistente patawallet/i })).toBeVisible()
  await page.getByRole('link', { name: /asistente patawallet/i }).click()
  await expect(page.getByRole('heading', { name: 'Asistente PataWallet' })).toBeVisible()
  await expect(page.getByText('Disponible para cuentas reales')).toBeVisible()
})

test('no produce desplazamiento horizontal', async ({ page }) => {
  await page.goto('/')
  const demoButton = page.getByRole('button', { name: /probar con datos de ejemplo/i })
  await expect(demoButton).toBeVisible()
  await demoButton.click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('mantiene cuentas legibles y reinicia el scroll al cambiar de ruta', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.evaluate(() => window.scrollTo(0, 500))
  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Tu dinero, de un vistazo', exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.scrollY)).toBe(0)

  const layout = await page.locator('.account-row').first().evaluate((row) => {
    const rowRect = row.getBoundingClientRect()
    const [icon, details, amount, edit, archive] = Array.from(row.children).map((item) => item.getBoundingClientRect())
    return { detailsAfterIcon: details.left > icon.right, amountInside: amount.right <= rowRect.right, actionsInside: archive.right <= rowRect.right && edit.right <= rowRect.right }
  })
  expect(layout.detailsAfterIcon).toBe(true)
  expect(layout.amountInside).toBe(true)
  expect(layout.actionsInside).toBe(true)
})

test('registra un gasto y lo conserva al recargar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.getByRole('textbox', { name: /Monto/i }).fill('10.000')
  await page.getByLabel(/Categoría/).selectOption({ label: 'Mascotas' })
  await page.getByRole('textbox', { name: /Comercio o nota/i }).fill('Compra de prueba')
  await page.getByRole('button', { name: 'Guardar movimiento' }).click()
  await page.getByRole('link', { name: 'Actividad' }).click()
  await expect(page.getByText('Compra de prueba')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Compra de prueba')).toBeVisible()
})

test('oculta montos y aplica las preferencias de tema y movimiento', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: /ajustes/i }).first().click()
  await page.getByRole('switch', { name: 'Ocultar montos' }).click()
  await expect(page.getByText('Modo nocturno')).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Tema' })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Movimiento' }).selectOption('off')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'off')
  await page.getByRole('link', { name: 'Inicio' }).click()
  await expect(page.getByText('••••••').first()).toBeVisible()
})

test('abre notificaciones sin solicitar permiso automáticamente', async ({ page }) => {
  await page.addInitScript(() => {
    window.__permissionRequests = 0
    class TestNotification {}
    TestNotification.permission = 'default'
    TestNotification.requestPermission = async () => { window.__permissionRequests += 1; return 'default' }
    Object.defineProperty(window, 'Notification', { value: TestNotification, configurable: true })
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Probar con datos de ejemplo' }).click()
  await page.goto('/ajustes/notificaciones')
  await expect(page.getByRole('heading', { name: 'Avisos privados de PataWallet' })).toBeVisible()
  await expect(page.getByText('Solo para cuentas reales')).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.__permissionRequests)).toBe(0)
})

test('mantiene el foco dentro del movimiento y lo devuelve al cerrar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  const opener = page.getByRole('button', { name: 'Nuevo movimiento' })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Nuevo movimiento' })
  await expect(dialog).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar' }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.locator(':focus')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()
})

test('mantiene acciones accesibles en horizontal y con texto ampliado', async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.addStyleTag({ content: 'html { font-size: 200% !important; }' })
  const save = page.getByRole('button', { name: 'Guardar movimiento' })
  await save.scrollIntoViewIfNeeded()
  await expect(save).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('cierra y guarda las ventanas de metas', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Otra meta' }).click()
  await expect(page.getByRole('dialog', { name: 'Nueva meta' })).toBeVisible()
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByRole('button', { name: 'Cerrar' }).click()
  await expect(page.getByRole('dialog', { name: 'Nueva meta' })).toBeHidden()
  await page.getByRole('button', { name: 'Otra meta' }).click()
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByLabel('Nombre').fill('Viaje familiar')
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByLabel('Monto objetivo').fill('500.000')
  // Simula un doble toque rápido: la meta debe persistirse una sola vez.
  await page.getByRole('button', { name: 'Crear meta' }).click({ clickCount: 2 })
  await expect(page.locator('.plan-goal-list').getByText('Viaje familiar')).toHaveCount(1)
})

test('crea categoría, hora y comprobante opcionales', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.getByRole('button', { name: 'Crear categoría' }).click()
  const categoryDialog = page.getByRole('dialog', { name: 'Nueva categoría' })
  await categoryDialog.getByLabel('Nombre').fill('Educación')
  await categoryDialog.getByRole('button', { name: 'Crear categoría' }).click()
  await expect(page.locator('.field').filter({ hasText: /^Categoría/ }).locator('select')).toHaveValue(/category/)
  await page.getByRole('textbox', { name: /Monto/i }).fill('25.000')
  await page.getByLabel('Hora').fill('18:45')
  await page.locator('input[type=file]').setInputFiles({ name: 'comprobante.png', mimeType: 'image/png', buffer: Buffer.from('89504e470d0a1a0a', 'hex') })
  await expect(page.getByAltText('Vista previa del comprobante')).toBeVisible()
  await page.getByRole('button', { name: 'Guardar movimiento' }).click()
  await expect(page.getByText('Movimiento guardado')).toBeVisible()
})

test('agrega y evalúa una próxima compra sin crear gasto', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Agregar' }).click()
  const dialog = page.getByRole('dialog', { name: 'Agregar próxima compra' })
  await dialog.getByLabel('Compra').fill('Audífonos')
  await dialog.getByLabel('Monto estimado').fill('120.000')
  // Simula un doble toque rápido: la próxima compra debe persistirse una sola vez.
  await dialog.getByRole('button', { name: 'Guardar próxima compra' }).click({ clickCount: 2 })
  const purchaseCard = page.locator('.plan-purchase-card')
  await expect(purchaseCard.getByRole('heading', { name: 'Audífonos' })).toHaveCount(1)
  await expect(page.locator('.toast')).toHaveCount(0)
  const evaluateButton = purchaseCard.getByRole('button', { name: 'Evaluar compra' })
  await evaluateButton.evaluate((element) => element.scrollIntoView({ block: 'center', behavior: 'instant' }))
  await evaluateButton.click()
  const assessment = purchaseCard.getByRole('status')
  await expect(assessment).toBeVisible()
  await expect(assessment).toContainText(/Puedes hacerla|No es recomendable|Falta información/)
})

test('crea una categoría desde una próxima compra', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  // El CTA del plan comparte la animación de entrada del panel en móvil.
  await page.getByRole('button', { name: 'Agregar' }).click({ force: true })
  const dialog = page.getByRole('dialog', { name: 'Agregar próxima compra' })
  // En el viewport móvil el botón puede quedar dentro de un contenedor animado; fuerza el clic
  // solo después de resolver el botón para validar el evento real sin depender de la estabilidad del transform.
  await dialog.getByRole('button', { name: 'Crear categoría' }).click({ force: true })
  const categoryDialog = page.getByRole('dialog', { name: 'Nueva categoría' })
  await categoryDialog.getByLabel('Nombre').fill('Hogar')
  await categoryDialog.getByRole('button', { name: 'Crear categoría' }).click({ force: true })
  await expect(dialog.locator('.field').filter({ hasText: /^Categoría/ }).locator('select')).toHaveValue(/.+/)
})
