import { expect, test } from '@playwright/test'

test('entra a la demo y navega por las áreas principales', async ({ page }) => {
  await page.goto('/')
  const demoButton = page.getByRole('button', { name: /probar con datos de ejemplo/i })
  await expect(demoButton).toBeVisible()
  await demoButton.click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.getByRole('link', { name: 'Actividad' }).click()
  await expect(page).toHaveURL(/\/actividad$/)
  await expect(page.getByRole('heading', { name: 'Actividad' })).toBeVisible()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await expect(page).toHaveURL(/\/plan$/)
  await expect(page.getByRole('heading', { name: 'Metas y plan' })).toBeVisible()
})

test('abre el asistente desde la burbuja flotante', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('link', { name: 'Abrir asistente' })).toBeVisible()
  await page.getByRole('link', { name: 'Abrir asistente' }).click()
  await expect(page).toHaveURL(/\/asistente$/)
  await expect(page.getByRole('heading', { name: 'Asistente PataWallet' })).toBeVisible()
})

test('abre la guía de uso desde Ajustes y recorre sus pasos', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.goto('/ajustes')
  await page.getByRole('button', { name: 'Ver guía' }).click()
  const guide = page.getByRole('dialog')
  await expect(guide).toBeVisible()
  await expect(guide.getByText('1 de 4')).toBeVisible()
  await guide.getByRole('button', { name: 'Siguiente' }).click()
  await expect(page.getByRole('heading', { name: 'Empieza por lo que tienes hoy.' })).toBeVisible()
  await guide.getByRole('button', { name: 'Siguiente' }).click()
  await expect(page.getByRole('heading', { name: 'El botón + guarda lo que pasó.' })).toBeVisible()
  await guide.getByRole('button', { name: 'Siguiente' }).click()
  await guide.getByRole('button', { name: 'Empezar a usar PataWallet' }).click()
  await expect(guide).toHaveCount(0)
})

test('entra sin encuesta y puede registrar su saldo desde Cuentas', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Configurar mi espacio' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Probar con datos de ejemplo' }).click()
  await expect(page.getByRole('heading', { name: /Hola,/i })).toBeVisible()
  await expect(page.getByText('Dinero registrado en cuentas').first()).toBeVisible()
  await page.goto('/cuentas?agregar-cuenta=1')
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta' })
  await expect(accountDialog).toBeVisible()
  await accountDialog.getByLabel('Nombre').fill('Ahorros Bancolombia')
  await accountDialog.getByLabel('Saldo inicial').fill('3.200.000')
  await accountDialog.getByRole('button', { name: 'Crear cuenta' }).click()
  await expect(page.getByRole('heading', { name: 'Ahorros Bancolombia', exact: true })).toBeVisible()
  await expect(page.locator('.account-row').filter({ hasText: 'Ahorros Bancolombia' })).toContainText('3.200.000')
  await expect(page).toHaveURL(/\/cuentas$/)
})

test('muestra el resumen rápido de metas, compras y cuentas en Inicio', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: 'Metas', exact: true })).toBeVisible()
  await expect(page.getByText('Un viaje especial')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Próximas compras', exact: true })).toBeVisible()
  await expect(page.getByText('Sin compras anotadas')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Cuentas', exact: true })).toBeVisible()
  await expect(page.getByText('Cuenta principal', { exact: true })).toBeVisible()
})

test('cambia y recuerda las tres vistas de Inicio', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  const views = page.getByRole('group', { name: 'Vistas de Inicio' })
  await expect(views.getByRole('button', { name: 'Saldo claro' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('Dinero registrado en cuentas').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)

  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  const fixedExpenses = page.locator('.fixed-expenses-section')
  await fixedExpenses.getByRole('button', { name: 'Gastos fijos', exact: true }).click()
  await fixedExpenses.getByLabel('Nombre').fill('Internet de prueba')
  await fixedExpenses.getByLabel('Monto mensual').fill('80.000')
  await fixedExpenses.getByRole('button', { name: 'Guardar gastos fijos' }).click()
  await expect(page.getByText('Gastos fijos guardados')).toBeVisible()
  await page.getByRole('link', { name: 'Inicio', exact: true }).click()

  await views.getByRole('button', { name: 'Quincena' }).click()
  await expect(page.getByRole('heading', { name: 'Tu fecha de pago' })).toBeVisible()
  await expect(views.getByRole('button', { name: 'Quincena' })).toHaveAttribute('aria-pressed', 'true')
  const payment = page.getByRole('checkbox', { name: /Marcar Internet de prueba del .* como pagado/ }).first()
  await expect(payment).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.reload()
  await expect(views.getByRole('button', { name: 'Quincena' })).toHaveAttribute('aria-pressed', 'true')
  const recurringPayment = page.getByRole('checkbox', { name: /Marcar Internet de prueba del .* como pagado/ }).first()
  await expect(recurringPayment).not.toBeChecked()

  await views.getByRole('button', { name: 'Actividad' }).click()
  await expect(page.getByRole('heading', { name: 'Gastos por categoría' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Actividad' })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('registra un plan opcional de deuda y un ingreso recibido', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.goto('/cuentas')
  await page.getByRole('button', { name: 'Agregar deuda', exact: true }).click()
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta' })
  await expect(accountDialog.getByLabel('Naturaleza')).toHaveValue('liability')
  await accountDialog.getByLabel('Nombre').fill('Libre inversión')
  await accountDialog.getByLabel('Tipo de deuda').selectOption('investment_loan')
  await accountDialog.getByLabel('Deuda inicial').fill('1.200.000')
  await accountDialog.getByLabel('Total de cuotas').fill('12')
  await accountDialog.getByLabel('Cuotas pagadas').fill('2')
  await accountDialog.getByLabel('Valor de cada cuota').fill('100.000')
  await accountDialog.getByLabel('Cada cuánto la pagas').selectOption('monthly')
  await accountDialog.getByRole('button', { name: 'Crear cuenta' }).click()
  await expect(page.getByRole('heading', { name: 'Libre inversión', exact: true })).toBeVisible()
  await expect(page.getByText(/2 de 12 cuotas · .* cada mes/)).toBeVisible()

  const fixedExpenses = page.locator('.fixed-expenses-section')
  await expect(fixedExpenses.locator('form')).toHaveCount(0)

  const incomeSection = page.locator('.income-section')
  await expect(incomeSection.locator('form')).toHaveCount(0)
  await incomeSection.getByRole('button', { name: 'Ingresos', exact: true }).click()
  await incomeSection.getByRole('button', { name: 'Registrar dinero recibido' }).click()
  const incomeDialog = page.getByRole('dialog', { name: 'Nuevo movimiento' })
  await expect(incomeDialog.getByRole('button', { name: 'Recibí dinero' })).toHaveAttribute('aria-pressed', 'true')
  await incomeDialog.getByRole('textbox', { name: /^Monto/ }).fill('3.200.000')
  await incomeDialog.getByLabel('Categoría', { exact: true }).selectOption({ index: 1 })
  await incomeDialog.getByRole('button', { name: 'Guardar movimiento' }).click()
  await expect(page.getByText('Movimiento guardado')).toBeVisible()

  await page.goto('/ajustes')
  await expect(page.getByRole('heading', { name: 'Ingresos', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Gastos fijos', exact: true })).toHaveCount(0)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Ingresos recibidos', exact: true })).toBeVisible()
  await expect(page.locator('.income-summary').getByText(/6\.400\.000/)).toBeVisible()
})

test('confirma un pago en Cuentas y conserva la marca al guardar y recargar', async ({ page }, testInfo) => {
  const browserErrors = []
  page.on('pageerror', (error) => browserErrors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })

  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/i })).toBeVisible()
  await page.goto('/cuentas')
  await expect(page.getByRole('heading', { name: 'Tu dinero, de un vistazo', exact: true })).toBeVisible()

  const fixedExpenses = page.locator('.fixed-expenses-section')
  await fixedExpenses.getByRole('button', { name: 'Gastos fijos', exact: true }).click()
  await fixedExpenses.getByLabel('Nombre').fill('Arriendo de prueba')
  await fixedExpenses.getByLabel('Monto mensual').fill('900.000')
  await fixedExpenses.getByRole('button', { name: 'Guardar gastos fijos' }).click()
  await expect(page.getByText('Gastos fijos guardados')).toBeVisible()

  const payment = fixedExpenses.locator('.recurring-payment').filter({ hasText: 'Arriendo de prueba' }).first().getByRole('checkbox')
  const paymentLabel = await payment.getAttribute('aria-label')
  await payment.click()
  const confirmation = page.getByRole('dialog', { name: 'Confirmar pago' })
  await expect(confirmation).toBeVisible()
  await confirmation.screenshot({ path: testInfo.outputPath('payment-confirmation.png'), animations: 'disabled' })
  await confirmation.getByLabel('Categoría').selectOption({ label: 'Mercado' })
  await confirmation.getByRole('button', { name: 'Sí, registrar pago' }).click()
  await expect(page.getByText('Arriendo de prueba pagado y registrado')).toBeVisible()
  await expect(page.getByRole('checkbox', { name: paymentLabel })).toHaveCount(0)
  await page.goto('/actividad')
  await expect(page.getByText('Arriendo de prueba').first()).toBeVisible()
  await page.goto('/cuentas')
  await fixedExpenses.getByRole('button', { name: 'Gastos fijos', exact: true }).click()

  await fixedExpenses.getByRole('button', { name: 'Guardar gastos fijos' }).click()
  await expect(page.getByText('Gastos fijos guardados')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Tu dinero, de un vistazo', exact: true })).toBeVisible()
  await fixedExpenses.getByRole('button', { name: 'Gastos fijos', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: paymentLabel })).toHaveCount(0)
  expect(browserErrors).toEqual([])
})

test('limita pagos quincenales a dos y confirma la marca también en Quincena', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  await expect(page).toHaveURL(/\/cuentas$/)
  await expect(page.getByRole('heading', { name: 'Tu dinero, de un vistazo', exact: true })).toBeVisible()

  const fixedExpenses = page.locator('.fixed-expenses-section')
  await fixedExpenses.getByRole('button', { name: 'Gastos fijos', exact: true }).click()
  await fixedExpenses.getByLabel('Nombre').fill('Mercado quincenal')
  await fixedExpenses.getByLabel('Monto mensual').fill('400.000')
  await fixedExpenses.getByLabel('¿Cada cuánto se hace este pago?').selectOption('biweekly')
  await fixedExpenses.getByLabel('Monto por pago').fill('400.000')
  const dueDate = await page.evaluate(() => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Bogota' }).format(new Date()))
  await fixedExpenses.getByLabel('Próxima fecha de pago').fill(dueDate)
  await fixedExpenses.getByRole('button', { name: 'Guardar gastos fijos' }).click()

  const accountPayments = fixedExpenses.locator('.recurring-payment').filter({ hasText: 'Mercado quincenal' })
  await expect(accountPayments).toHaveCount(2)
  const accountCheckbox = accountPayments.getByRole('checkbox').first()
  await accountCheckbox.click()
  const accountConfirmation = page.getByRole('dialog', { name: 'Confirmar pago' })
  await expect(accountConfirmation).toBeVisible()
  await accountConfirmation.getByRole('button', { name: 'Todavía no' }).click()
  await expect(accountCheckbox).not.toBeChecked()

  await page.getByRole('link', { name: 'Inicio', exact: true }).click()
  const views = page.getByRole('group', { name: 'Vistas de Inicio' })
  await views.getByRole('button', { name: 'Quincena' }).click()
  const paydayPayments = page.locator('.dashboard-payment').filter({ hasText: 'Mercado quincenal' })
  await expect(paydayPayments).toHaveCount(2)
  const paydayCheckbox = paydayPayments.getByRole('checkbox').first()
  const paydayPaymentLabel = await paydayCheckbox.getAttribute('aria-label')
  await paydayCheckbox.evaluate((element) => element.scrollIntoView({ block: 'center', behavior: 'instant' }))
  await paydayCheckbox.click()
  const confirmation = page.getByRole('dialog', { name: 'Confirmar pago' })
  await expect(confirmation).toBeVisible()
  await confirmation.getByLabel('Categoría').selectOption({ label: 'Mercado' })
  await confirmation.getByRole('button', { name: 'Sí, registrar pago' }).click()
  await expect(page.getByText('Mercado quincenal pagado y registrado')).toBeVisible()
  await expect(page.getByRole('checkbox', { name: paydayPaymentLabel })).toHaveCount(0)
  await expect(paydayPayments).toHaveCount(2)
})

test('muestra el acceso al asistente y protege la demo', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.goto('/ajustes')
  await expect(page.getByRole('link', { name: /asistente patawallet/i })).toBeVisible()
  await page.getByRole('link', { name: /asistente patawallet/i }).click()
  await expect(page.getByRole('heading', { name: 'Asistente PataWallet' })).toBeVisible()
  await expect(page.getByText('Disponible para cuentas reales')).toBeVisible()
})

test('no produce desplazamiento horizontal', async ({ page }) => {
  await page.goto('/')
  const demoButton = page.getByRole('button', { name: /probar con datos de ejemplo/i })
  await expect(demoButton).toBeVisible()
  await demoButton.click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('mantiene cuentas legibles y reinicia el scroll al cambiar de ruta', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.evaluate(() => window.scrollTo(0, 500))
  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Tu dinero, de un vistazo', exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.scrollY)).toBe(0)

  const layout = await page.locator('.account-row').first().evaluate((row) => {
    const rowRect = row.getBoundingClientRect()
    const [icon, details, amount, edit, archive] = Array.from(row.children).map((item) => item.getBoundingClientRect())
    return { detailsAfterIcon: details.left > icon.right, amountInside: amount.right <= rowRect.right, actionsInside: archive.right <= rowRect.right && edit.right <= rowRect.right }
  })
  expect(layout.detailsAfterIcon).toBe(true)
  expect(layout.amountInside).toBe(true)
  expect(layout.actionsInside).toBe(true)
})

test('registra un gasto y lo conserva al recargar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.getByRole('textbox', { name: /Monto/i }).fill('10.000')
  await page.getByLabel(/Categoría/).selectOption({ label: 'Mascotas' })
  await page.getByRole('button', { name: 'Añadir detalles' }).click()
  await page.getByRole('textbox', { name: /Comercio o nota/i }).fill('Compra de prueba')
  await page.getByRole('button', { name: 'Guardar movimiento' }).click()
  await page.getByRole('link', { name: 'Actividad' }).click()
  await expect(page.getByText('Compra de prueba')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Compra de prueba')).toBeVisible()
})

test('ofrece caminos claros para ingreso, compra con crédito, pago de deuda y movimiento propio', async ({ page }) => {
  test.setTimeout(60000)
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()

  const open = async () => {
    await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
    return page.getByRole('dialog', { name: 'Nuevo movimiento' })
  }
  let dialog = await open()
  await dialog.getByRole('button', { name: 'Recibí dinero' }).click()
  await dialog.getByRole('textbox', { name: /Monto/i }).fill('20.000')
  await dialog.getByLabel('¿Dónde lo recibiste?').selectOption({ label: 'Cuenta principal' })
  await dialog.getByLabel('Categoría', { exact: true }).selectOption({ label: 'Salario' })
  await dialog.getByRole('button', { name: 'Guardar movimiento' }).click()

  dialog = await open()
  await dialog.getByRole('button', { name: 'Hice una compra' }).click()
  await dialog.getByRole('textbox', { name: /Monto/i }).fill('15.000')
  await dialog.getByLabel('¿Con qué pagaste?').selectOption({ label: 'Tarjeta de ejemplo (crédito)' })
  await dialog.getByLabel('Categoría', { exact: true }).selectOption({ label: 'Mercado' })
  await dialog.getByRole('button', { name: 'Guardar movimiento' }).click()

  dialog = await open()
  await dialog.getByRole('button', { name: 'Pagué una deuda' }).click()
  await dialog.getByRole('textbox', { name: /Monto/i }).fill('10.000')
  await dialog.getByLabel('¿De dónde salió el dinero?').selectOption({ label: 'Cuenta principal' })
  await dialog.getByLabel('¿Qué deuda pagaste?').selectOption({ label: 'Tarjeta de ejemplo' })
  await dialog.getByRole('button', { name: 'Guardar movimiento' }).click()

  dialog = await open()
  await dialog.getByRole('button', { name: 'Más opciones: moví dinero' }).click()
  await dialog.getByRole('button', { name: 'Moví dinero' }).click()
  await dialog.getByRole('textbox', { name: /Monto/i }).fill('5.000')
  await dialog.getByLabel('¿De dónde salió el dinero?').selectOption({ label: 'Cuenta principal' })
  await dialog.getByLabel('¿A qué cuenta lo moviste?').selectOption({ label: 'Efectivo' })
  await dialog.getByRole('button', { name: 'Guardar movimiento' }).click()

  await page.getByRole('link', { name: 'Actividad', exact: true }).click()
  await expect(page.locator('.transaction-group .transaction').filter({ hasText: 'Pago de deuda' }).filter({ hasText: '10.000' })).toHaveCount(1)
  await expect(page.locator('.transaction-group .transaction').filter({ hasText: 'Transferencia' }).filter({ hasText: '5.000' })).toHaveCount(1)
})

test('permite confirmar un monto antiguo como saldo actual sin volverlo a escribir', async ({ page }) => {
  test.setTimeout(60000)
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.evaluate(async () => {
    const { db } = await import('/src/data/db.js')
    await db.settings.put({ key: 'monthlySalaryMinor', value: 185980000 })
  })
  await page.goto('/cuentas')
  page.on('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Archivar Cuenta principal' }).click()
  await expect(page.getByRole('button', { name: 'Archivar Cuenta principal' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Archivar Efectivo' }).click()
  await expect(page.getByText('Aún no hay dinero disponible registrado.')).toBeVisible()
  await page.goto('/')
  await expect(page.getByText('Aún sin cuenta')).toBeVisible()
  await expect(page.getByRole('link', { name: /Revísalo y confirma cuánto tienes hoy/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.getByRole('link', { name: /Revísalo y confirma cuánto tienes hoy/ }).click()
  const account = page.getByRole('dialog', { name: 'Agregar cuenta' })
  await expect(account.getByLabel('Saldo inicial')).toHaveValue('1.859.800')
  await account.getByLabel('Nombre').fill('Mi banco')
  await account.getByRole('button', { name: 'Crear cuenta' }).click()
  await expect(account).toBeHidden()
  await page.goto('/')
  await expect(page.locator('.dashboard-available-hero strong').first()).toContainText('1.859.800')
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  const movement = page.getByRole('dialog', { name: 'Nuevo movimiento' })
  await movement.getByRole('button', { name: 'Pagué una deuda' }).click()
  await expect(movement.getByLabel('¿De dónde salió el dinero?')).toHaveValue(/.+/)
  await movement.getByRole('textbox', { name: /Monto/i }).fill('10.000')
  await movement.getByRole('button', { name: 'Guardar movimiento' }).click()
  await expect(movement).toBeHidden()
  await page.goto('/')
  await expect(page.locator('.dashboard-available-hero strong').first()).toContainText('1.849.800')
  await page.goto('/cuentas')
  await expect(page.getByRole('heading', { name: 'Mi banco' })).toBeVisible()
  await expect(page.locator('.accounts-ledger__pane--asset .account-row').filter({ hasText: 'Mi banco' })).toContainText('1.849.800')
})

test('oculta montos y aplica las preferencias de tema y movimiento', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: /ajustes/i }).first().click()
  await page.getByRole('switch', { name: 'Ocultar montos' }).click()
  await expect(page.getByText('Modo nocturno')).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Tema' })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Movimiento' }).selectOption('off')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'off')
  await page.getByRole('link', { name: 'Inicio' }).click()
  await expect(page.getByText('••••••').first()).toBeVisible()
})

test('abre notificaciones sin solicitar permiso automáticamente', async ({ page }) => {
  await page.addInitScript(() => {
    window.__permissionRequests = 0
    class TestNotification {}
    TestNotification.permission = 'default'
    TestNotification.requestPermission = async () => { window.__permissionRequests += 1; return 'default' }
    Object.defineProperty(window, 'Notification', { value: TestNotification, configurable: true })
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Probar con datos de ejemplo' }).click()
  await expect(page.getByRole('heading', { name: /hola, danilo/i })).toBeVisible()
  await page.goto('/ajustes/notificaciones')
  await expect(page.getByRole('heading', { name: 'Avisos privados de PataWallet' })).toBeVisible()
  await expect(page.getByText('Solo para cuentas reales')).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.__permissionRequests)).toBe(0)
})

test('mantiene el foco dentro del movimiento y lo devuelve al cerrar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  const opener = page.getByRole('button', { name: 'Nuevo movimiento' })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Nuevo movimiento' })
  await expect(dialog).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar' }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.locator(':focus')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()
})

test('mantiene acciones accesibles en horizontal y con texto ampliado', async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.addStyleTag({ content: 'html { font-size: 200% !important; }' })
  const save = page.getByRole('button', { name: 'Guardar movimiento' })
  await save.scrollIntoViewIfNeeded()
  await expect(save).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test('cierra y guarda las ventanas de metas', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Otra meta' }).click()
  await expect(page.getByRole('dialog', { name: 'Nueva meta' })).toBeVisible()
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByRole('button', { name: 'Cerrar' }).click()
  await expect(page.getByRole('dialog', { name: 'Nueva meta' })).toBeHidden()
  await page.getByRole('button', { name: 'Otra meta' }).click()
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByLabel('Nombre').fill('Viaje familiar')
  await page.getByRole('dialog', { name: 'Nueva meta' }).getByLabel('Monto objetivo').fill('500.000')
  // Simula un doble toque rápido: la meta debe persistirse una sola vez.
  await page.getByRole('button', { name: 'Crear meta' }).click({ clickCount: 2 })
  await expect(page.locator('.plan-goal-list').getByText('Viaje familiar')).toHaveCount(1)
})

test('crea categoría, hora y comprobante opcionales', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('button', { name: 'Nuevo movimiento' }).click()
  await page.getByRole('button', { name: 'Crear categoría' }).click()
  const categoryDialog = page.getByRole('dialog', { name: 'Nueva categoría' })
  await categoryDialog.getByLabel('Nombre').fill('Educación')
  await categoryDialog.getByRole('button', { name: 'Crear categoría' }).click()
  await expect(page.locator('.field').filter({ hasText: /^Categoría/ }).locator('select')).toHaveValue(/category/)
  await page.getByRole('textbox', { name: /Monto/i }).fill('25.000')
  await page.getByRole('button', { name: 'Añadir detalles' }).click()
  await page.getByLabel('Hora').fill('18:45')
  await page.locator('input[type=file]').setInputFiles({ name: 'comprobante.png', mimeType: 'image/png', buffer: Buffer.from('89504e470d0a1a0a', 'hex') })
  await expect(page.getByAltText('Vista previa del comprobante')).toBeVisible()
  await page.getByRole('button', { name: 'Guardar movimiento' }).click()
  await expect(page.getByText('Movimiento guardado')).toBeVisible()
})

test('agrega y evalúa una próxima compra sin crear gasto', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Agregar' }).click()
  const dialog = page.getByRole('dialog', { name: 'Agregar próxima compra' })
  await dialog.getByLabel('Compra').fill('Audífonos')
  await dialog.getByLabel('Monto estimado').fill('120.000')
  // Simula un doble toque rápido: la próxima compra debe persistirse una sola vez.
  await dialog.getByRole('button', { name: 'Guardar próxima compra' }).click({ clickCount: 2 })
  const purchaseCard = page.locator('.plan-purchase-card')
  await expect(purchaseCard.getByRole('heading', { name: 'Audífonos' })).toHaveCount(1)
  await expect(page.locator('.toast')).toHaveCount(0)
  const evaluateButton = purchaseCard.getByRole('button', { name: 'Evaluar compra' })
  await evaluateButton.evaluate((element) => element.scrollIntoView({ block: 'center', behavior: 'instant' }))
  await evaluateButton.click()
  const assessment = purchaseCard.getByRole('status')
  await expect(assessment).toBeVisible()
  await expect(assessment).toContainText(/Puedes hacerla|No es recomendable|Falta información/)
})

test('crea una categoría desde una próxima compra', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: 'Plan', exact: true }).click()
  // Espera a que el CTA termine su animación antes de interactuar en móvil.
  await page.getByRole('button', { name: 'Agregar' }).click()
  const dialog = page.getByRole('dialog', { name: 'Agregar próxima compra' })
  await dialog.getByRole('button', { name: 'Crear categoría' }).click()
  const categoryDialog = page.getByRole('dialog', { name: 'Nueva categoría' })
  await categoryDialog.getByLabel('Nombre').fill('Hogar')
  await categoryDialog.getByRole('button', { name: 'Crear categoría' }).click()
  await expect(dialog.locator('.field').filter({ hasText: /^Categoría/ }).locator('select')).toHaveValue(/.+/)
})
