import { expect, test } from '@playwright/test'

// Datos sintéticos locales: comprueba escala y edición sin tocar finanzas remotas.
test('30 gastos se mantienen compactos, buscables y editables sin perder pagos', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/i })).toBeVisible()
  const originalTransactions = await page.evaluate(async () => {
    const { db } = await import('/src/data/db.js')
    const { calendarToday } = await import('/src/domain/recurringExpenses.js')
    const today = calendarToday()
    const [year, month] = today.split('-').map(Number)
    const previousMonthStart = new Date(Date.UTC(year, month - 2, 1, 12)).toISOString().slice(0, 10)
    const nextMonthStart = new Date(Date.UTC(year, month, 1, 12)).toISOString().slice(0, 10)
    await db.settings.put({ key: 'fixedExpenses', value: Array.from({ length: 30 }, (_, i) => ({
      id: `fixture-${i}`, name: `Servicio ${String(i + 1).padStart(2, '0')}`, amount_minor: 15000000,
      frequency: i === 0 ? 'biweekly' : 'monthly', next_due_date: i === 0 ? previousMonthStart : i === 1 ? nextMonthStart : today, currency: 'COP', category_id: null,
      payment_history: [{ due_date: '2026-01-01', paid_at: '2026-01-01T12:00:00Z', status: 'paid' }],
    })) })
    return db.transactions.toArray()
  })
  await page.goto('/cuentas#gastos-fijos')
  const section = page.locator('.fixed-expenses-section')
  await expect(section.locator('.fixed-expense-summary')).toHaveCount(5)
  await expect(section.locator('form')).toHaveCount(0)
  await page.goto('/cuentas/pagos')
  const periods = page.locator('.recurring-payments__group')
  expect(await periods.count()).toBeGreaterThanOrEqual(3)
  await expect(periods.nth(0).locator(':scope > summary')).toContainText('Atrasados')
  await expect(periods.nth(0)).toHaveAttribute('open', '')
  const repeatedExpense = periods.nth(0).locator('.recurring-payment-series')
  await expect(repeatedExpense.locator('summary')).toContainText('2 vencimientos')
  await expect(repeatedExpense).not.toHaveAttribute('open', '')
  await repeatedExpense.locator('summary').click()
  await expect(repeatedExpense.locator('.recurring-payment--nested')).toHaveCount(2)
  await repeatedExpense.locator('summary').click()
  await expect(periods.nth(1)).toHaveAttribute('open', '')
  await expect(periods.nth(2)).not.toHaveAttribute('open', '')
  await expect(periods.nth(1).locator('.recurring-payment')).toHaveCount(6)
  // Verifica que las secciones plegables sigan cabiendo en los tamaños móviles requeridos.
  for (const viewport of [{ width: 390, height: 844 }, { width: 375, height: 812 }, { width: 1440, height: 900 }]) {
    await page.setViewportSize(viewport)
    await expect(periods.nth(1).locator(':scope > summary')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/cuentas/gastos-fijos')
  await expect(section.getByRole('navigation', { name: 'Páginas de gastos fijos' })).toContainText('1–5 de 30')
  await section.getByRole('button', { name: 'Gastos fijos: siguientes' }).click()
  await expect(section.getByRole('button', { name: 'Editar Servicio 06', exact: true })).toBeVisible()
  await section.getByRole('button', { name: 'Gastos fijos: anteriores' }).click()
  await section.getByLabel('Buscar gasto fijo').fill('no existe')
  await expect(section.getByText('No encontramos gastos con ese nombre.')).toBeVisible()
  await section.getByLabel('Buscar gasto fijo').fill('Servicio 30')
  await expect(section.locator('.fixed-expense-summary')).toHaveCount(1)
  const opener = section.getByRole('button', { name: 'Editar Servicio 30', exact: true })
  await opener.click()
  const editor = page.getByRole('dialog', { name: 'Editar gasto fijo', exact: true })
  await expect(page.locator('.app-shell')).toHaveAttribute('inert', '')
  await editor.getByLabel('Monto mensual').fill('0')
  await editor.getByRole('button', { name: 'Guardar gasto fijo' }).click()
  await expect(editor.getByRole('alert')).toContainText('mayor que cero')
  await expect(editor.getByLabel('Nombre')).toHaveValue('Servicio 30')
  await editor.getByLabel('Monto mensual').fill('200.000')
  await editor.getByRole('button', { name: 'Guardar gasto fijo' }).click()
  await expect(editor).toHaveCount(0)
  await expect(opener).toBeFocused()
  await expect(opener).toContainText('200.000')
  const updated = await page.evaluate(async () => (await (await import('/src/data/db.js')).db.settings.get('fixedExpenses')).value)
  expect(updated).toHaveLength(30)
  expect(updated[29].payment_history[0].due_date).toBe('2026-01-01')
  expect(updated[29].amount_minor).toBe(20000000)

  // Cancelar no cambia datos y Escape restaura el foco al control que abrió el diálogo.
  await opener.click()
  await editor.getByLabel('Nombre').fill('No guardar')
  await page.keyboard.press('Escape')
  await expect(opener).toBeFocused()
  await opener.click()
  await editor.getByRole('button', { name: 'Eliminar gasto fijo', exact: true }).click()
  const confirmation = page.getByRole('dialog', { name: 'Eliminar gasto fijo', exact: true })
  await expect(confirmation).toContainText('Los movimientos que ya registraste no se borrarán')
  await confirmation.getByRole('button', { name: 'Volver a editar' }).click()
  await editor.getByRole('button', { name: 'Eliminar gasto fijo', exact: true }).click()
  await confirmation.getByRole('button', { name: 'Sí, eliminar gasto fijo' }).click()
  await expect(confirmation).toHaveCount(0)
  await section.getByLabel('Buscar gasto fijo').fill('')
  await expect(section.getByRole('navigation', { name: 'Páginas de gastos fijos' })).toContainText('de 29')

  await section.getByRole('button', { name: 'Agregar gasto fijo' }).click()
  const adding = page.getByRole('dialog', { name: 'Agregar gasto fijo', exact: true })
  await adding.getByLabel('Nombre').fill('Internet nuevo')
  await adding.getByLabel('Monto mensual').fill('85.000')
  await adding.getByRole('button', { name: 'Guardar gasto fijo' }).click()
  await expect(adding).toHaveCount(0)
  await page.reload()
  await expect(section.locator('.fixed-expense-summary')).toHaveCount(5)
  await expect(section.getByRole('navigation', { name: 'Páginas de gastos fijos' })).toContainText('de 30')
  await page.goto('/cuentas/pagos')
  await page.getByRole('button', { name: /Gastos de .*: siguientes/ }).click()
  await expect(page.getByRole('navigation', { name: /Páginas de gastos de/ })).toContainText('7–12')
  await page.getByRole('button', { name: /Gastos de .*: anteriores/ }).click()
  await page.goto('/cuentas/gastos-fijos')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await section.evaluate((el) => el.scrollIntoView({ block: 'start', behavior: 'instant' }))
  await page.screenshot({ path: `output/playwright/fixed-expenses-${testInfo.project.name}.png` })
  expect(await page.evaluate(async () => (await import('/src/data/db.js')).db.transactions.toArray())).toEqual(originalTransactions)
  expect(errors).toEqual([])
})

// Simula un fallo de guardado real de la capa local y verifica recuperación, privacidad y offline.
test('editor conserva borrador en error, respeta montos ocultos y guarda offline', async ({ page, context }) => {
  test.setTimeout(60000)
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/i })).toBeVisible()
  await page.goto('/cuentas#gastos-fijos')
  const section = page.locator('.fixed-expenses-section')
  await expect(section.getByText(/Aún no tienes gastos fijos/)).toBeVisible()
  await section.getByRole('button', { name: 'Agregar gasto fijo' }).click()
  const editor = page.getByRole('dialog', { name: 'Agregar gasto fijo', exact: true })
  await editor.getByLabel('Nombre').fill('Internet')
  await editor.getByLabel('Monto mensual').fill('150.000')
  await page.evaluate(async () => {
    const { db } = await import('/src/data/db.js')
    const original = db.settings.put.bind(db.settings)
    db.settings.put = async (...args) => {
      if (args[0].key !== 'fixedExpenses') return original(...args)
      db.settings.put = original
      throw new Error('Fallo de guardado de prueba')
    }
  })
  await editor.getByRole('button', { name: 'Guardar gasto fijo' }).click()
  await expect(editor.getByRole('alert')).toHaveText('Fallo de guardado de prueba')
  await expect(editor.getByLabel('Monto mensual')).toHaveValue('150.000')
  await context.setOffline(true)
  await editor.getByRole('button', { name: 'Guardar gasto fijo' }).click()
  await expect(editor).toHaveCount(0)
  await expect(section.getByRole('button', { name: 'Editar Internet' })).toBeVisible()
  await context.setOffline(false)
  await page.evaluate(async () => {
    const { db } = await import('/src/data/db.js')
    await db.settings.put({ key: 'hiddenAmounts', value: true })
  })
  await expect(section.locator('.fixed-expense-summary__amount')).toHaveText('••••••')
  await expect(section.locator('.fixed-expenses-hero')).toContainText('••••••')
  await page.goto('/cuentas/pagos')
  await expect(page.locator('.recurring-payment__amount').first()).toHaveText('••••••')
})
