import { expect, test } from '@playwright/test'

// Comprueba que convertir una compra a un abono usa una cuenta de dinero real como origen.
test('corrige el origen al cambiar de compra con tarjeta a pago de deuda', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/ })).toBeVisible()
  await page.getByRole('button', { name: 'Nuevo movimiento', exact: true }).click()
  await page.getByRole('combobox', { name: '¿Con qué pagaste?' }).selectOption({ label: 'Tarjeta de ejemplo (crédito)' })
  await page.getByRole('button', { name: 'Pagué una deuda', exact: true }).click()
  const source = page.getByLabel('¿De dónde salió el dinero?', { exact: true })
  const destination = page.getByLabel('¿Qué deuda pagaste?', { exact: true })
  await expect(source).toHaveValue(await source.locator('option').first().getAttribute('value'))
  await expect(destination.locator('option:checked')).toHaveText('Tarjeta de ejemplo')
  await page.getByRole('textbox', { name: /^Monto/ }).fill('50.000')
  await page.getByRole('button', { name: 'Guardar movimiento', exact: true }).click()
  await expect(page.getByText('Movimiento guardado', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Actividad', exact: true }).click()
  await expect(page.locator('.transaction').filter({ hasText: 'Pago de deuda' }).filter({ hasText: '50.000' })).toHaveCount(1)
})

// Prepara únicamente la demo aislada para reproducir un usuario con deudas y sin dinero registrado.
test('crea el origen sin perder el borrador cuando solo hay deudas', async ({ page }, testInfo) => {
  // Incluye alta, cancelación, guardado y recarga; WebKit móvil necesita más que un flujo simple.
  test.setTimeout(60000)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/ })).toBeVisible()
  await archiveDemoAssets(page)
  await page.reload()
  await page.getByRole('button', { name: 'Nuevo movimiento', exact: true }).click()
  await page.getByRole('button', { name: 'Pagué una deuda', exact: true }).click()
  await expect(page.getByLabel('¿De dónde salió el dinero?', { exact: true })).toBeDisabled()
  await expect(page.getByText('Agrega una cuenta con el saldo que tienes hoy para registrar de dónde salió el dinero.')).toBeVisible()
  await page.getByRole('textbox', { name: /^Monto/ }).fill('97.100')
  await page.getByRole('button', { name: 'Añadir detalles' }).click()
  await page.getByLabel('Comercio o nota').fill('Abono de prueba')
  await page.getByRole('button', { name: 'Agregar cuenta' }).click()
  await page.getByRole('dialog', { name: 'Agregar cuenta', exact: true }).getByLabel('Nombre', { exact: true }).fill('Mi efectivo')
  // Escape cierra únicamente el diálogo hijo y conserva los datos del movimiento.
  await page.keyboard.press('Escape')
  await expect(page.getByRole('heading', { name: 'Nuevo movimiento', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Agregar cuenta' }).click()
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta', exact: true })
  await accountDialog.getByLabel('Nombre', { exact: true }).fill('Mi efectivo')
  await accountDialog.getByRole('combobox', { name: /^Tipo de cuenta/ }).selectOption('cash')
  await accountDialog.getByLabel('Saldo inicial').fill('200.000')
  await accountDialog.getByRole('button', { name: 'Crear cuenta', exact: true }).click()
  await expect(accountDialog).toBeHidden()
  await expect(page.getByLabel('¿De dónde salió el dinero?', { exact: true }).locator('option:checked')).toHaveText('Mi efectivo')
  await expect(page.getByRole('textbox', { name: /^Monto/ })).toHaveValue('97.100')
  await expect(page.getByLabel('Comercio o nota')).toHaveValue('Abono de prueba')
  await page.getByLabel('¿De dónde salió el dinero?', { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('transfer-account.png') })
  await page.getByRole('button', { name: 'Guardar movimiento', exact: true }).click()
  await expect(page.getByText('Movimiento guardado', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('link', { name: 'Actividad', exact: true }).click()
  const payment = page.locator('.transaction').filter({ hasText: 'Abono de prueba' })
  await expect(payment).toHaveCount(1)
  await expect(payment).toContainText('Pago de deuda')
  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  // 200.000 − 97.100 en efectivo y 185.000 − 97.100 de deuda: un solo abono.
  await expect(page.locator('.account-row').filter({ hasText: 'Mi efectivo' })).toContainText('102.900')
  await expect(page.locator('.account-row').filter({ hasText: 'Tarjeta de ejemplo' })).toContainText('87.900')
  expect(errors).toEqual([])
})

// Reproduce una compra ordinaria cuando el usuario solo tenía tarjetas de deuda registradas.
test('permite registrar una compra desde dinero disponible recién agregado', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/ })).toBeVisible()
  await archiveDemoAssets(page)
  await page.reload()
  await page.getByRole('button', { name: 'Nuevo movimiento', exact: true }).click()
  await expect(page.getByLabel('¿Con qué pagaste?').locator('option:checked')).toHaveText('Selecciona una cuenta')
  await page.getByRole('textbox', { name: /^Monto/ }).fill('50.000')
  await page.getByRole('button', { name: 'Agregar cuenta' }).click()
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta', exact: true })
  await accountDialog.getByLabel('Nombre', { exact: true }).fill('Cuenta donde cobro')
  await accountDialog.getByLabel('Saldo inicial').fill('200.000')
  await accountDialog.getByRole('button', { name: 'Crear cuenta', exact: true }).click()
  await expect(page.getByLabel('¿Con qué pagaste?').locator('option:checked')).toHaveText('Cuenta donde cobro')
  await expect(page.getByRole('textbox', { name: /^Monto/ })).toHaveValue('50.000')
  await page.getByLabel('Categoría', { exact: true }).selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Guardar movimiento', exact: true }).click()
  await expect(page.getByText('Movimiento guardado', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  await expect(page.locator('.account-row').filter({ hasText: 'Cuenta donde cobro' })).toContainText('150.000')
})

// Una compra nueva siempre señala la cuenta real que pagó; no crea gastos huérfanos.
test('impide guardar una compra sin cuenta y actualiza el saldo tras agregarla', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/ })).toBeVisible()
  await archiveDemoAssets(page)
  await page.reload()
  await page.getByRole('button', { name: 'Nuevo movimiento', exact: true }).click()
  await expect(page.getByLabel('¿Con qué pagaste?').locator('option')).toHaveCount(2)
  await expect(page.getByLabel('¿Con qué pagaste?').locator('option:checked')).toHaveText('Selecciona una cuenta')
  await page.getByRole('textbox', { name: /^Monto/ }).fill('25.000')
  await page.getByLabel('Categoría', { exact: true }).selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Agregar cuenta' }).click()
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta', exact: true })
  await accountDialog.getByLabel('Nombre', { exact: true }).fill('Mi banco')
  await accountDialog.getByLabel('Saldo inicial').fill('100.000')
  await accountDialog.getByRole('button', { name: 'Crear cuenta' }).click()
  await expect(accountDialog).toBeHidden()
  await page.getByRole('button', { name: 'Añadir detalles' }).click()
  await page.getByLabel('Comercio o nota').fill('Compra cotidiana')
  await page.getByRole('button', { name: 'Guardar movimiento', exact: true }).click()
  await expect(page.getByText('Movimiento guardado', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Actividad', exact: true }).click()
  const purchase = page.locator('.transaction').filter({ hasText: 'Compra cotidiana' })
  await expect(purchase).toHaveCount(1)
  await expect(purchase).toContainText('Mi banco')
  await expect(purchase).toContainText('25.000')
  await page.reload()
  await expect(page.locator('.transaction').filter({ hasText: 'Compra cotidiana' })).toHaveCount(1)
  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  await expect(page.locator('.account-row').filter({ hasText: 'Mi banco' })).toContainText('75.000')
  await expect(page.locator('.account-row').filter({ hasText: 'Tarjeta de ejemplo' })).toContainText('185.000')
})

// Archiva solo los activos ficticios de la demo para comprobar el estado de solo deudas.
async function archiveDemoAssets(page) {
  await page.evaluate(async () => {
    const { db } = await import('/src/data/db.js')
    const assets = await db.accounts.filter((account) => account.kind === 'asset').toArray()
    await db.accounts.bulkPut(assets.map((account) => ({ ...account, archived: true })))
  })
}
