import { expect, test } from '@playwright/test'

// Comprueba que convertir una compra a un abono usa una cuenta de dinero real como origen.
test('corrige el origen al cambiar de gasto con tarjeta a transferencia', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/ })).toBeVisible()
  await page.getByRole('button', { name: 'Nuevo movimiento', exact: true }).click()
  await page.getByRole('combobox', { name: /^Cuenta/ }).selectOption({ label: 'Tarjeta de ejemplo' })
  await page.getByRole('button', { name: 'Transferencia', exact: true }).click()
  const source = page.getByLabel('Desde', { exact: true })
  const destination = page.getByLabel('Hacia', { exact: true })
  await expect(source).toHaveValue(await source.locator('option').first().getAttribute('value'))
  await expect(destination.locator('option:checked')).toHaveText('Tarjeta de ejemplo (pago de deuda)')
  await page.getByRole('textbox', { name: /^Monto/ }).fill('50.000')
  await page.getByRole('button', { name: 'Guardar movimiento', exact: true }).click()
  await expect(page.getByText('Movimiento guardado', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Actividad', exact: true }).click()
  await expect(page.locator('.transaction').filter({ hasText: 'Pago de deuda' }).filter({ hasText: '50.000' })).toHaveCount(1)
})

// Prepara únicamente la demo aislada para reproducir un usuario con deudas y sin dinero registrado.
test('crea el origen sin perder el borrador cuando solo hay deudas', async ({ page }, testInfo) => {
  // Incluye alta, cancelación, guardado y recarga; WebKit móvil necesita más que un flujo simple.
  test.setTimeout(60000)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: /Hola, Danilo/ })).toBeVisible()
  await page.evaluate(async () => {
    const { db } = await import('/src/data/db.js')
    const assets = await db.accounts.filter((account) => account.kind === 'asset').toArray()
    await db.accounts.bulkPut(assets.map((account) => ({ ...account, archived: true })))
  })
  await page.reload()
  await page.getByRole('button', { name: 'Nuevo movimiento', exact: true }).click()
  await page.getByRole('button', { name: 'Transferencia', exact: true }).click()
  await expect(page.getByLabel('Desde', { exact: true })).toBeDisabled()
  await expect(page.getByText('Agrega efectivo, una cuenta bancaria o una billetera para indicar de dónde sale el pago.')).toBeVisible()
  await page.getByRole('textbox', { name: /^Monto/ }).fill('97.100')
  await page.getByLabel('Comercio o nota').fill('Abono de prueba')
  await page.getByRole('button', { name: 'Agregar cuenta de origen' }).click()
  await page.getByRole('dialog', { name: 'Agregar cuenta', exact: true }).getByLabel('Nombre', { exact: true }).fill('Mi efectivo')
  // Escape cierra únicamente el diálogo hijo y conserva los datos del movimiento.
  await page.keyboard.press('Escape')
  await expect(page.getByRole('heading', { name: 'Nuevo movimiento', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Agregar cuenta de origen' }).click()
  const accountDialog = page.getByRole('dialog', { name: 'Agregar cuenta', exact: true })
  await accountDialog.getByLabel('Nombre', { exact: true }).fill('Mi efectivo')
  await accountDialog.getByRole('combobox', { name: /^Tipo de cuenta/ }).selectOption('cash')
  await accountDialog.getByLabel('Saldo inicial').fill('200.000')
  await accountDialog.getByRole('button', { name: 'Crear cuenta', exact: true }).click()
  await expect(accountDialog).toBeHidden()
  await expect(page.getByLabel('Desde', { exact: true }).locator('option:checked')).toHaveText('Mi efectivo')
  await expect(page.getByRole('textbox', { name: /^Monto/ })).toHaveValue('97.100')
  await expect(page.getByLabel('Comercio o nota')).toHaveValue('Abono de prueba')
  await page.getByLabel('Desde', { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('transfer-account.png') })
  await page.getByRole('button', { name: 'Guardar movimiento', exact: true }).click()
  await expect(page.getByText('Movimiento guardado', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('link', { name: 'Actividad', exact: true }).click()
  const payment = page.locator('.transaction').filter({ hasText: 'Abono de prueba' })
  await expect(payment).toHaveCount(1)
  await expect(payment).toContainText('Pago de deuda')
  await page.getByRole('link', { name: 'Cuentas', exact: true }).click()
  // 200.000 − 97.100 en efectivo y 185.000 − 97.100 de deuda: un solo abono.
  await expect(page.locator('.account-row').filter({ hasText: 'Mi efectivo' })).toContainText('102.900')
  await expect(page.locator('.account-row').filter({ hasText: 'Tarjeta de ejemplo' })).toContainText('87.900')
  expect(errors).toEqual([])
})
