import { expect, test } from '@playwright/test'

test('presenta el flujo de Atajos con estados honestos y sin enlace falso', async ({ page }, testInfo) => {
  const consoleErrors = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await expect(page.getByRole('heading', { name: 'Hola, Danilo' })).toBeVisible()
  await page.goto('/ajustes/automatizacion')
  await expect(page.getByRole('heading', { name: 'PataWallet - Registrar compra' })).toBeVisible()
  await expect(page.getByText('Plantilla pendiente de publicar').first()).toBeVisible()
  await expect(page.getByRole('button', { name: /Añadir atajo — pendiente/i })).toBeDisabled()
  const tutorialLink = page.getByRole('link', { name: /abrir el tutorial de automatización en video/i })
  await expect(tutorialLink).toHaveAttribute('href', '/assets/integrations/tutorial-patawallet-paso-a-paso.mp4')
  await expect(tutorialLink).toHaveAttribute('target', '_blank')
  if (testInfo.project.name === 'desktop') {
    const videoResponse = await page.request.get(await tutorialLink.getAttribute('href'))
    expect(videoResponse.ok()).toBe(true)
    expect(videoResponse.headers()['content-type']).toContain('video/mp4')
  }
  await expect(page.locator('.shortcut-instructions > li')).toHaveCount(7)
  await expect(page.locator('.shortcut-instructions')).toContainText('amount')
  await expect(page.locator('.shortcut-instructions')).toContainText('Tarjeta o pase')
  await expect(page.getByText(/prueba no crea gastos/i)).toBeVisible()
  await expect(page.getByText(/no se anuncia una cola/i)).toBeVisible()
  expect(await page.locator('a[href*="icloud.com/shortcuts"]').count()).toBe(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.screenshot({ path: `output/playwright/tutorial-shortcuts-${testInfo.project.name}.png`, fullPage: true })
  expect(consoleErrors).toEqual([])
})

test('conserva Automatización usable en noche y con movimiento reducido', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile-390', 'Una captura móvil representativa basta para esta variante.')
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' })
  await page.goto('/')
  await page.getByRole('button', { name: /probar con datos de ejemplo/i }).click()
  await page.getByRole('link', { name: /ajustes/i }).first().click()
  await expect(page.getByRole('combobox', { name: 'Tema' })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Movimiento' }).selectOption('off')
  await page.goto('/ajustes/automatizacion')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'off')
  await expect(page.getByRole('heading', { name: 'Automatización' })).toBeVisible()
  await expect(page.getByRole('link', { name: /abrir el tutorial de automatización en video/i })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.screenshot({ path: 'output/playwright/tutorial-shortcuts-mobile-dark.png', fullPage: true })
})
