import { Link2Off, Trash2 } from 'lucide-react'

const dateLabel = (value) => value ? new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Sin registro'

export function ShortcutManagement({ integration, accounts, categories, notify }) {
  const active = integration.devices.filter((item) => item.status === 'active' || item.status === 'incomplete')
  return <div className="shortcut-management">
    <section className="shortcut-section"><div className="section-heading"><div><h2>Vinculaciones</h2><p>El acceso se puede revocar sin borrar movimientos ya registrados.</p></div></div>
      <div className="shortcut-list">{active.length ? active.map((item) => <article className="shortcut-row shortcut-row--device" key={item.id}><div><strong>{item.label} {item.status === 'incomplete' && <span className="status-label">Guardado sin verificar</span>}</strong><p>Automatización: {item.automation_declared_at ? 'declarada por ti, no verificada por la app' : 'sin confirmar'} · Última prueba: {dateLabel(item.last_test_at)} · Último evento real: {dateLabel(item.last_event_at)}</p></div><div className="shortcut-row__actions"><button className="compact-action" onClick={async () => { await integration.declareAutomation(item.id, !item.automation_declared_at); notify(item.automation_declared_at ? 'Declaración retirada' : 'Marcada como configurada por ti') }}>{item.automation_declared_at ? 'Retirar declaración' : 'La configuré'}</button><button className="compact-action danger-text" onClick={async () => { if (confirm('¿Revocar este acceso? La automatización seguirá en el iPhone hasta que la desactives allí.')) { await integration.revoke(item.id); notify('Acceso revocado') } }}><Link2Off /> Revocar</button></div></article>) : <p className="empty-inline">No hay dispositivos vinculados.</p>}</div>
    </section>
    <section className="shortcut-section"><div className="section-heading"><div><h2>Asociación inteligente</h2><p>{integration.categoryAiAvailable ? 'Gemini y OpenAI clasifican comercios nuevos; un tercer modelo solo desempata si discrepan.' : 'La clasificación con IA está pendiente de configuración.'} Solo se guarda con consenso; si no lo hay o falla un servicio, el movimiento queda para revisión. Cuando detectemos una tarjeta nueva, elegirás la cuenta una vez y la recordaremos.</p></div></div>
      {integration.mappings.length > 0 && <><h3>Tarjetas recordadas</h3><p>Se guardaron cuando confirmaste a qué cuenta pertenece cada una.</p><div className="shortcut-list">{integration.mappings.map((item) => <article className="shortcut-row" key={item.id}><div><strong>{item.card_alias}</strong><p>{accounts.find((account) => account.id === item.account_id)?.name || 'Cuenta archivada'}</p></div><button className="icon-button" aria-label={`Eliminar asociación ${item.card_alias}`} onClick={() => integration.deleteMapping(item.id)}><Trash2 /></button></article>)}</div></>}
      {integration.rules.length > 0 && <><h3>Comercios aprendidos</h3><p>La categoría se reutiliza solo para ese comercio exacto.</p><div className="shortcut-list">{integration.rules.map((item) => <article className="shortcut-row" key={item.id}><div><strong>{item.merchant_pattern}</strong><p>{categories.find((category) => category.id === item.category_id)?.name || 'Categoría eliminada'}</p></div><button className="icon-button" aria-label={`Eliminar categoría sugerida para ${item.merchant_pattern}`} onClick={() => integration.deleteRule(item.id)}><Trash2 /></button></article>)}</div></>}
    </section>
  </div>
}
